# Generated by Django 4.2.5 on 2023-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_student2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2023',
            name='age',
            field=models.IntegerField(),
        ),
    ]
