# Generated by Django 4.2.5 on 2023-10-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_alter_student2023_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'my table',
            },
        ),
    ]
