# Generated by Django 4.2.6 on 2023-10-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0006_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('regfile', models.FileField(upload_to='media')),
            ],
        ),
    ]
