# Generated by Django 4.2.6 on 2023-10-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_registrationfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeepoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.employee')),
            ],
        ),
    ]
