# Generated by Django 4.2.6 on 2023-10-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0010_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
